
name: sphinx-doc

on:
  push:
    branches:    
    - main

    paths:
    - src/docs/**

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: src/docs/_build/html/
