name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' 
        architecture: 'x64' 
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Download dependencies
      run: pip install pytest numpy  
    - name: Running tests
      run: pytest tests
